// This file is automatically generated by Firebase Studio.
//
// To change the Firebase project, use the "Change Firebase Project" command.
// You can get this config from the Firebase console.
export const firebaseConfig = {
  apiKey: "AIzaSyDxYrjGP3fFV4WvjRNsc5TXsZbTj_-5eU4",
  authDomain: "studio-7809189829-1bbe1.firebaseapp.com",
  projectId: "studio-7809189829-1bbe1",
  storageBucket: "studio-7809189829-1bbe1.appspot.com",
  messagingSenderId: "764116991788",
  appId: "1:764116991788:web:f60e68d5cb14c93a4cf689",
};
